apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80


# create pod with kubectl apply -f simplePod.yaml
# check labels kubectl get pods --show-labels
