apiVersion: v1
kind: Pod
metadata:
  name: configmap-secret-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      # you can define env here also.
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
      - name: secret
        mountPath: "/secret"
        readOnly: true
        
  volumes:
  # You set volumes at the Pod level, then mount them into containers inside that Pod
  - name: config
    configMap:
      # Provide the name of the ConfigMap you want to mount.
      name: pods-config

  # This is for secrets
  - name: secret
    secret:
      secretName: mysecret
      optional: false # default setting; "mysecret" must exist